import {
  User,
  Department,
  Position,
  Employee,
  Contract,
  ContractTemplate,
  DocumentItem,
  Vacation,
  Absence,
  PayrollSheet,
  SalaryHistory,
  NotificationItem,
  AuditLog,
  CompanySettings,
  VisualSettings,
  RolePermissions,
} from '../src/types/index.ts';

export const initialCompanySettings: CompanySettings = {
  companyName: 'GESTÃO EMPRESARIAL RH',
  commercialName: 'Grupo Empresarial Delta & Associados, Lda.',
  nif: '5412984102',
  address: 'Avenida 4 de Fevereiro, Edifício Atlântico Tower, 8º Andar',
  municipality: 'Luanda',
  province: 'Luanda',
  phone: '+244 923 456 789 / +244 222 345 678',
  email: 'geral@delta-empresarial.com',
  website: 'https://www.delta-empresarial.com',
  logoUrl: '/company_logo.jpg',
  responsibleName: 'Dr. António Manuel de Sousa',
  responsiblePosition: 'Diretor Geral de Recursos Humanos',
};

export const initialVisualSettings: VisualSettings = {
  primaryColor: '#1e3a8a', // Deep Blue
  secondaryColor: '#2563eb', // Royal Blue
  darkMode: false,
  contractExpiryNoticeDays: 30,
  documentExpiryNoticeDays: 30,
  currencySymbol: 'Kz',
};

export const initialRoles: RolePermissions[] = [
  {
    role: 'ADMINISTRADOR',
    description: 'Acesso total a todos os módulos, configurações e auditoria do sistema.',
    permissions: {
      employees: ['view', 'create', 'edit', 'delete'],
      contracts: ['view', 'create', 'edit', 'delete', 'approve', 'print'],
      documents: ['view', 'upload', 'download', 'delete'],
      vacations: ['view', 'create', 'edit', 'approve', 'delete'],
      absences: ['view', 'create', 'edit', 'delete'],
      salaries: ['view', 'create', 'edit', 'export', 'delete'],
      reports: ['view', 'export', 'print'],
      settings: ['view', 'edit'],
    },
  },
  {
    role: 'RH',
    description: 'Gestão completa de funcionários, contratos, férias, faltas e documentos.',
    permissions: {
      employees: ['view', 'create', 'edit', 'delete'],
      contracts: ['view', 'create', 'edit', 'approve', 'print'],
      documents: ['view', 'upload', 'download', 'delete'],
      vacations: ['view', 'create', 'edit', 'approve', 'delete'],
      absences: ['view', 'create', 'edit', 'delete'],
      salaries: ['view'],
      reports: ['view', 'export', 'print'],
      settings: ['view'],
    },
  },
  {
    role: 'CONTABILIDADE',
    description: 'Acesso a salários, histórico financeiro, folhas salariais e relatórios.',
    permissions: {
      employees: ['view'],
      contracts: ['view', 'print'],
      documents: ['view', 'download'],
      vacations: ['view'],
      absences: ['view'],
      salaries: ['view', 'create', 'edit', 'export', 'delete'],
      reports: ['view', 'export', 'print'],
      settings: ['view'],
    },
  },
  {
    role: 'GESTOR',
    description: 'Consulta de equipas, aprovação de férias e visualização de relatórios departamentais.',
    permissions: {
      employees: ['view'],
      contracts: ['view'],
      documents: ['view', 'download'],
      vacations: ['view', 'approve'],
      absences: ['view', 'create'],
      salaries: ['view'],
      reports: ['view', 'print'],
      settings: ['view'],
    },
  },
  {
    role: 'UTILIZADOR',
    description: 'Acesso básico para consulta de informações e solicitação de documentos.',
    permissions: {
      employees: ['view'],
      contracts: ['view'],
      documents: ['view', 'download'],
      vacations: ['view', 'create'],
      absences: ['view'],
      salaries: ['view'],
      reports: ['view'],
      settings: ['view'],
    },
  },
];

export const initialUsers: User[] = [
  {
    id: 'usr-1',
    code: 'ADM-001',
    name: 'Carlos Alberto Ferreira',
    email: 'admin@delta-empresarial.com',
    role: 'ADMINISTRADOR',
    password: 'admin123',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
    active: true,
    createdAt: '2025-01-10T08:00:00Z',
  },
  {
    id: 'usr-2',
    code: 'RH-001',
    name: 'Ana Paula Lourenço',
    email: 'ana.rh@delta-empresarial.com',
    role: 'RH',
    password: 'admin123',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    active: true,
    createdAt: '2025-01-12T09:30:00Z',
  },
  {
    id: 'usr-3',
    code: 'FIN-001',
    name: 'Manuel Sebastião Neves',
    email: 'manuel.contab@delta-empresarial.com',
    role: 'CONTABILIDADE',
    password: 'admin123',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    active: true,
    createdAt: '2025-01-15T11:00:00Z',
  },
  {
    id: 'usr-4',
    code: 'GEST-001',
    name: 'Margarida dos Santos',
    email: 'margarida.gestora@delta-empresarial.com',
    role: 'GESTOR',
    password: 'admin123',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    active: true,
    createdAt: '2025-02-01T14:15:00Z',
  },
  {
    id: 'usr-5',
    code: 'EMP-001',
    name: 'João Pedro da Silva',
    email: 'joao.colaborador@delta-empresarial.com',
    role: 'UTILIZADOR',
    isEmployeeOnly: true,
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    active: true,
    createdAt: '2025-02-10T10:00:00Z',
  },
];

export const initialDepartments: Department[] = [
  { id: 'dep-1', code: 'RH', name: 'Recursos Humanos', managerName: 'Ana Paula Lourenço', description: 'Gestão de pessoas, talentos e administração laboral' },
  { id: 'dep-2', code: 'FIN', name: 'Contabilidade e Finanças', managerName: 'Manuel Sebastião Neves', description: 'Gestão financeira, fiscalidade e tesouraria' },
  { id: 'dep-3', code: 'TI', name: 'Tecnologia da Informação', managerName: 'Carlos Ferreira', description: 'Infraestrutura tecnológica, sistemas e segurança' },
  { id: 'dep-4', code: 'COM', name: 'Comercial e Vendas', managerName: 'Margarida dos Santos', description: 'Prospeção de clientes, contratos comerciais e pós-venda' },
  { id: 'dep-5', code: 'LOG', name: 'Operações e Logística', managerName: 'Bernardo Afonso', description: 'Cadeia de suprimentos, frotas e armazenamento' },
  { id: 'dep-6', code: 'JUR', name: 'Gabinete Jurídico', managerName: 'Dra. Luísa Gaspar', description: 'Assessoria jurídica, conformidade e contencioso' },
];

export const initialPositions: Position[] = [
  { id: 'pos-1', title: 'Responsável de Recursos Humanos', departmentId: 'dep-1', baseSalaryMin: 650000, baseSalaryMax: 950000 },
  { id: 'pos-2', title: 'Técnico Sénior de RH', departmentId: 'dep-1', baseSalaryMin: 350000, baseSalaryMax: 550000 },
  { id: 'pos-3', title: 'Contabilista Sénior', departmentId: 'dep-2', baseSalaryMin: 600000, baseSalaryMax: 850000 },
  { id: 'pos-4', title: 'Assistente Financeiro', departmentId: 'dep-2', baseSalaryMin: 280000, baseSalaryMax: 420000 },
  { id: 'pos-5', title: 'Engenheiro de Software Sénior', departmentId: 'dep-3', baseSalaryMin: 800000, baseSalaryMax: 1300000 },
  { id: 'pos-6', title: 'Administrador de Redes e Infraestrutura', departmentId: 'dep-3', baseSalaryMin: 550000, baseSalaryMax: 850000 },
  { id: 'pos-7', title: 'Gestor Comercial e de Contas', departmentId: 'dep-4', baseSalaryMin: 450000, baseSalaryMax: 750000 },
  { id: 'pos-8', title: 'Coordenador de Logística e Armazém', departmentId: 'dep-5', baseSalaryMin: 400000, baseSalaryMax: 650000 },
  { id: 'pos-9', title: 'Consultor Jurídico', departmentId: 'dep-6', baseSalaryMin: 700000, baseSalaryMax: 1100000 },
];

export const initialEmployees: Employee[] = [
  {
    id: 'emp-1',
    code: 'EMP-001',
    fullName: 'Mateus Domingos Cassoma',
    nickname: 'Mateus',
    gender: 'MASCULINO',
    birthDate: '1988-06-14',
    nationality: 'Angolana',
    maritalStatus: 'CASADO',
    idNumber: '003418291LA042',
    idIssueDate: '2020-04-10',
    idExpiryDate: '2030-04-10',
    nif: '003418291LA042',
    phone: '+244 924 111 222',
    email: 'mateus.cassoma@delta-empresarial.com',
    address: 'Rua Rainha Ginga, Prédio 45, Apt 3B',
    municipality: 'Ingombota',
    province: 'Luanda',
    photoUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80',
    positionId: 'pos-5',
    positionName: 'Engenheiro de Software Sénior',
    departmentId: 'dep-3',
    departmentName: 'Tecnologia da Informação',
    jobRole: 'Líder Técnico de Sistemas e Infraestrutura',
    admissionDate: '2021-03-01',
    contractType: 'TEMPO_INDETERMINADO',
    contractStartDate: '2021-03-01',
    status: 'ATIVO',
    baseSalary: 950000,
    bankName: 'Banco Angolano de Investimentos (BAI)',
    accountNumber: '1428590123',
    iban: 'AO06004000001428590123101',
    socialSecurityNumber: 'SS-9041284',
    emergencyContactName: 'Esperança Cassoma',
    emergencyContactRelation: 'Esposa',
    emergencyContactPhone: '+244 931 999 888',
    emergencyContactAddress: 'Rua Rainha Ginga, Prédio 45, Apt 3B, Luanda',
    notes: 'Colaborador com excelente desempenho técnico, certificado em arquitetura cloud.',
    createdAt: '2021-03-01T08:00:00Z',
    updatedAt: '2026-01-15T10:00:00Z',
  },
  {
    id: 'emp-2',
    code: 'EMP-002',
    fullName: 'Cláudia Beatriz de Oliveira',
    nickname: 'Cláudia',
    gender: 'FEMININO',
    birthDate: '1992-11-23',
    nationality: 'Angolana',
    maritalStatus: 'SOLTEIRO',
    idNumber: '005829103LA039',
    idIssueDate: '2021-08-15',
    idExpiryDate: '2031-08-15',
    nif: '005829103LA039',
    phone: '+244 923 888 777',
    email: 'claudia.oliveira@delta-empresarial.com',
    address: 'Condomínio Bela Vista, Bloco C, Casa 12',
    municipality: 'Talatona',
    province: 'Luanda',
    photoUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=200&auto=format&fit=crop&q=80',
    positionId: 'pos-2',
    positionName: 'Técnico Sénior de RH',
    departmentId: 'dep-1',
    departmentName: 'Recursos Humanos',
    jobRole: 'Responsável pelo Processamento Salarial e Admissões',
    admissionDate: '2022-05-15',
    contractType: 'TERMO_CERTO',
    contractStartDate: '2025-10-01',
    contractEndDate: '2026-10-01', // Expiring in approx 10 days relative to 2026-09-22! Alert!
    status: 'ATIVO',
    baseSalary: 480000,
    bankName: 'Banco Millennium Atlântico (BMA)',
    accountNumber: '9847120394',
    iban: 'AO06005500009847120394102',
    socialSecurityNumber: 'SS-7182934',
    emergencyContactName: 'Beatriz da Silva de Oliveira',
    emergencyContactRelation: 'Mãe',
    emergencyContactPhone: '+244 912 333 444',
    emergencyContactAddress: 'Bairro Miramar, Luanda',
    notes: 'Contrato a termo de 1 ano, renovação pendente de avaliação de desempenho.',
    createdAt: '2022-05-15T09:00:00Z',
    updatedAt: '2026-09-01T14:30:00Z',
  },
  {
    id: 'emp-3',
    code: 'EMP-003',
    fullName: 'Joaquim Alberto Quaresma',
    nickname: 'Quaresma',
    gender: 'MASCULINO',
    birthDate: '1985-02-18',
    nationality: 'Angolana',
    maritalStatus: 'CASADO',
    idNumber: '001928491LA015',
    idIssueDate: '2019-01-20',
    idExpiryDate: '2026-10-10', // Document expiring soon!
    nif: '001928491LA015',
    phone: '+244 945 666 555',
    email: 'joaquim.quaresma@delta-empresarial.com',
    address: 'Rua Comandante Gika, Edifício Garden, 4º D',
    municipality: 'Maianga',
    province: 'Luanda',
    photoUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&auto=format&fit=crop&q=80',
    positionId: 'pos-3',
    positionName: 'Contabilista Sénior',
    departmentId: 'dep-2',
    departmentName: 'Contabilidade e Finanças',
    jobRole: 'Supervisão Fiscal e Fecho de Contas Anuais',
    admissionDate: '2020-01-10',
    contractType: 'TEMPO_INDETERMINADO',
    contractStartDate: '2020-01-10',
    status: 'EM_FERIAS',
    baseSalary: 720000,
    bankName: 'Banco de Fomento Angola (BFA)',
    accountNumber: '4481029384',
    iban: 'AO06000600004481029384109',
    socialSecurityNumber: 'SS-5519283',
    emergencyContactName: 'Teresa Quaresma',
    emergencyContactRelation: 'Esposa',
    emergencyContactPhone: '+244 928 777 111',
    emergencyContactAddress: 'Rua Comandante Gika, Maianga, Luanda',
    notes: 'Em gozo de férias regulamentares autorizadas pela Direção Financeira.',
    createdAt: '2020-01-10T08:30:00Z',
    updatedAt: '2026-09-15T09:00:00Z',
  },
  {
    id: 'emp-4',
    code: 'EMP-004',
    fullName: 'Zacarias Francisco Gouveia',
    nickname: 'Zack',
    gender: 'MASCULINO',
    birthDate: '1995-07-30',
    nationality: 'Angolana',
    maritalStatus: 'SOLTEIRO',
    idNumber: '008912349LA058',
    idIssueDate: '2022-03-11',
    idExpiryDate: '2032-03-11',
    nif: '008912349LA058',
    phone: '+244 933 444 111',
    email: 'zacarias.gouveia@delta-empresarial.com',
    address: 'Bairro Cruzeiro, Rua 12, Vivenda 4',
    municipality: 'Cacuaco',
    province: 'Luanda',
    photoUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&auto=format&fit=crop&q=80',
    positionId: 'pos-8',
    positionName: 'Coordenador de Logística e Armazém',
    departmentId: 'dep-5',
    departmentName: 'Operações e Logística',
    jobRole: 'Controle de Frota, Cargas e Armazém Central',
    admissionDate: '2023-08-01',
    contractType: 'TERMO_CERTO',
    contractStartDate: '2024-09-15',
    contractEndDate: '2026-09-15', // Vencido recentemente! Alerta Vermelho!
    status: 'ATIVO',
    baseSalary: 450000,
    bankName: 'Banco Sol',
    accountNumber: '7729104812',
    iban: 'AO06004400007729104812105',
    socialSecurityNumber: 'SS-8819230',
    emergencyContactName: 'Mariana Gouveia',
    emergencyContactRelation: 'Irmã',
    emergencyContactPhone: '+244 911 222 999',
    emergencyContactAddress: 'Cacuaco, Luanda',
    notes: 'Atenção: Contrato terminou em 15/09/2026, necessária renovação imediata ou rescisão contratual.',
    createdAt: '2023-08-01T10:00:00Z',
    updatedAt: '2026-09-16T11:20:00Z',
  },
  {
    id: 'emp-5',
    code: 'EMP-005',
    fullName: 'Helena Maria de Carvalho',
    nickname: 'Helena',
    gender: 'FEMININO',
    birthDate: '1990-09-05',
    nationality: 'Angolana',
    maritalStatus: 'CASADO',
    idNumber: '004128930LA022',
    idIssueDate: '2019-06-18',
    idExpiryDate: '2029-06-18',
    nif: '004128930LA022',
    phone: '+244 929 555 444',
    email: 'helena.carvalho@delta-empresarial.com',
    address: 'Morro Bento, Rua das Acácias, Casa 8',
    municipality: 'Samba',
    province: 'Luanda',
    photoUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=200&auto=format&fit=crop&q=80',
    positionId: 'pos-7',
    positionName: 'Gestor Comercial e de Contas',
    departmentId: 'dep-4',
    departmentName: 'Comercial e Vendas',
    jobRole: 'Gestão de Grandes Clientes Corporativos e Propostas',
    admissionDate: '2022-02-01',
    contractType: 'TEMPO_INDETERMINADO',
    contractStartDate: '2022-02-01',
    status: 'ATIVO',
    baseSalary: 620000,
    bankName: 'Banco Angolano de Investimentos (BAI)',
    accountNumber: '3318290192',
    iban: 'AO06004000003318290192103',
    socialSecurityNumber: 'SS-4418290',
    emergencyContactName: 'Rui de Carvalho',
    emergencyContactRelation: 'Esposo',
    emergencyContactPhone: '+244 922 444 333',
    emergencyContactAddress: 'Morro Bento, Luanda',
    notes: 'Superou metas comerciais trimestrais de forma consistente.',
    createdAt: '2022-02-01T08:00:00Z',
    updatedAt: '2026-08-30T17:00:00Z',
  },
  {
    id: 'emp-6',
    code: 'EMP-006',
    fullName: 'Feliciano Pedro Ndongala',
    nickname: 'Feliciano',
    gender: 'MASCULINO',
    birthDate: '1998-04-12',
    nationality: 'Angolana',
    maritalStatus: 'SOLTEIRO',
    idNumber: '009823412LA071',
    idIssueDate: '2023-01-10',
    idExpiryDate: '2033-01-10',
    nif: '009823412LA071',
    phone: '+244 940 123 789',
    email: 'feliciano.ndongala@delta-empresarial.com',
    address: 'Centralidade do Kilamba, Bloco E21, Apt 104',
    municipality: 'Belas',
    province: 'Luanda',
    photoUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=200&auto=format&fit=crop&q=80',
    positionId: 'pos-6',
    positionName: 'Administrador de Redes e Infraestrutura',
    departmentId: 'dep-3',
    departmentName: 'Tecnologia da Informação',
    jobRole: 'Monitorização de Servidores, Firewalls e Suporte Nível 2',
    admissionDate: '2024-04-01',
    contractType: 'TERMO_CERTO',
    contractStartDate: '2024-04-01',
    contractEndDate: '2027-04-01',
    status: 'ATIVO',
    baseSalary: 550000,
    bankName: 'Banco Millennium Atlântico (BMA)',
    accountNumber: '5519283746',
    iban: 'AO06005500005519283746108',
    socialSecurityNumber: 'SS-9912841',
    emergencyContactName: 'Pedro Ndongala',
    emergencyContactRelation: 'Pai',
    emergencyContactPhone: '+244 923 111 000',
    emergencyContactAddress: 'Centralidade do Kilamba, Luanda',
    notes: 'Concluiu formação em segurança de redes e firewalls.',
    createdAt: '2024-04-01T09:00:00Z',
    updatedAt: '2026-06-20T15:00:00Z',
  },
];

export const initialContractTemplates: ContractTemplate[] = [
  {
    id: 'tpl-1',
    title: 'Contrato de Trabalho por Tempo Indeterminado (Efetivo)',
    description: 'Modelo padrão regulamentado para contratação permanente e estável.',
    type: 'TEMPO_INDETERMINADO',
    isDefault: true,
    content: `CONTRATO DE TRABALHO POR TEMPO INDETERMINADO

ENTRE AS PARTES:

PRIMEIRO OUTORGANTE:
{{NOME_EMPRESA}}, sociedade comercial por quotas, com sede em {{ENDERECO_EMPRESA}}, titular do Número de Identificação Fiscal (NIF) {{NIF_EMPRESA}}, adiante designada abreviadamente por "EMPREGADOR" ou "EMPRESA".

SEGUNDO OUTORGANTE:
{{NOME_FUNCIONARIO}}, portador(a) do Bilhete de Identidade / Passaporte nº {{BI}}, com o NIF nº {{NIF}}, residente em {{MORADA}}, adiante designado(a) por "TRABALHADOR".

É livremente e de boa fé celebrado o presente Contrato de Trabalho, que se rege pelas cláusulas seguintes:

CLÁUSULA 1ª (FUNÇÃO E CARGO)
O Empregador contrata o Trabalhador para exercer as funções inerentes ao cargo de {{CARGO}}, integrado no departamento de {{DEPARTAMENTO}}, desempenhando com zelo, lealdade e assiduidade todas as tarefas inerentes e compatíveis com a sua qualificação profissional.

CLÁUSULA 2ª (LOCAL E HORÁRIO DE TRABALHO)
1. O Trabalhador prestará serviço nas instalações da Empresa em {{ENDERECO_EMPRESA}}, ou noutros locais onde a Empresa desenvolva atividades.
2. O período normal de trabalho semanal é de 40 (quarenta) horas, distribuídas de segunda a sexta-feira, em harmonia com as disposições internas da Empresa.

CLÁUSULA 3ª (DURAÇÃO)
O presente contrato é celebrado por Tempo Indeterminado, com início de vigência e produção plena de efeitos a partir de {{DATA_INICIO}}.

CLÁUSULA 4ª (RETRIBUIÇÃO E SUBSÍDIOS)
1. Pela prestação de trabalho, a Empresa pagará ao Trabalhador a retribuição mensal base de {{SALARIO}}.
2. Sobre a retribuição incidirão os descontos legais e fiscais obrigatórios, acrescendo os subsídios aplicáveis nos termos da política de benefícios da Empresa.

CLÁUSULA 5ª (FÉRIAS E AUSÊNCIAS)
O Trabalhador tem direito a férias remuneradas anuais e regime de justificação de faltas conforme o regulamento interno e a legislação laboral aplicável.

CLÁUSULA 6ª (CONFIDENCIALIDADE E LEALDADE)
O Trabalhador compromete-se a guardar absoluto sigilo relativamente a todas as informações, segredos comerciais, dados de clientes e documentos a que tenha acesso no exercício das suas funções.

Feito em duplicado, ficando um exemplar na posse de cada uma das partes.

Luanda, aos {{DATA_INICIO}}

_________________________________________          _________________________________________
Pelo Primeiro Outorgante (EMPRESA)                   Pelo Segundo Outorgante (TRABALHADOR)`,
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2025-01-01T00:00:00Z',
  },
  {
    id: 'tpl-2',
    title: 'Contrato de Trabalho a Termo Certo',
    description: 'Modelo padrão para contratação com termo temporal pré-fixado.',
    type: 'TERMO_CERTO',
    isDefault: false,
    content: `CONTRATO DE TRABALHO A TERMO CERTO

ENTRE:
{{NOME_EMPRESA}}, com sede em {{ENDERECO_EMPRESA}}, NIF {{NIF_EMPRESA}}, doravante "EMPREGADOR".
E
{{NOME_FUNCIONARIO}}, portador(a) do BI {{BI}}, NIF {{NIF}}, residente em {{MORADA}}, doravante "TRABALHADOR".

CLÁUSULA 1ª (CARGO E ATRIBUIÇÕES)
O Trabalhador é contratado para a função de {{CARGO}} afeto ao departamento de {{DEPARTAMENTO}}.

CLÁUSULA 2ª (VIGÊNCIA E TERMO)
O presente contrato inicia-se formalmente em {{DATA_INICIO}} e vigorará até {{DATA_FIM}}, justificando-se a estipulação de termo pela necessidade transitória de reforço operacional e execução de projetos específicos.

CLÁUSULA 3ª (REMUNERAÇÃO)
O salário mensal acordado é de {{SALARIO}}, acrescido de subsídios de alimentação e transporte estipulados no regulamento empresarial.

Luanda, {{DATA_INICIO}}

___________________________                         ___________________________
A EMPRESA                                           O TRABALHADOR`,
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2025-01-01T00:00:00Z',
  },
  {
    id: 'tpl-3',
    title: 'Contrato de Prestação de Serviços Técnicos',
    description: 'Modelo civil/comercial para prestadores autônomos ou consultores.',
    type: 'PRESTACAO_SERVICOS',
    isDefault: false,
    content: `CONTRATO DE PRESTAÇÃO DE SERVIÇOS TÉCNICOS E CONSULTORIA

PRIMEIRO OUTORGANTE: {{NOME_EMPRESA}}, NIF {{NIF_EMPRESA}}, com sede em {{ENDERECO_EMPRESA}}.
SEGUNDO OUTORGANTE: {{NOME_FUNCIONARIO}}, NIF {{NIF}}, BI {{BI}}, residente em {{MORADA}}.

Objeto: Prestação de serviços especializados na área de {{CARGO}} para o departamento de {{DEPARTAMENTO}}.
Honorários acordados: {{SALARIO}} mensais contra entrega de nota fiscal/recibo de honorários.
Vigência: De {{DATA_INICIO}} a {{DATA_FIM}}.

Luanda, {{DATA_INICIO}}

___________________________                         ___________________________
CONTRATANTE                                         CONTRATADO`,
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2025-01-01T00:00:00Z',
  },
];

export const initialContracts: Contract[] = [
  {
    id: 'cnt-1',
    contractNumber: 'CTR-2021-001',
    employeeId: 'emp-1',
    employeeName: 'Mateus Domingos Cassoma',
    employeeCode: 'EMP-001',
    departmentName: 'Tecnologia da Informação',
    positionName: 'Engenheiro de Software Sénior',
    type: 'TEMPO_INDETERMINADO',
    typeName: 'Tempo Indeterminado',
    startDate: '2021-03-01',
    baseSalary: 950000,
    status: 'ATIVO',
    notes: 'Contrato efetivo com cláusula de confidencialidade reforçada.',
    signedDate: '2021-03-01',
    isSigned: true,
    createdAt: '2021-03-01T08:00:00Z',
    updatedAt: '2021-03-01T08:00:00Z',
  },
  {
    id: 'cnt-2',
    contractNumber: 'CTR-2025-042',
    employeeId: 'emp-2',
    employeeName: 'Cláudia Beatriz de Oliveira',
    employeeCode: 'EMP-002',
    departmentName: 'Recursos Humanos',
    positionName: 'Técnico Sénior de RH',
    type: 'TERMO_CERTO',
    typeName: 'Termo Certo (12 Meses)',
    startDate: '2025-10-01',
    endDate: '2026-10-01', // Próximo de vencer (< 30 dias)! Alerta AMARELO!
    durationMonths: 12,
    baseSalary: 480000,
    status: 'A_TERMINAR',
    notes: 'Vence em menos de 10 dias. Notificação emitida aos Recursos Humanos.',
    signedDate: '2025-10-01',
    isSigned: true,
    createdAt: '2025-10-01T09:00:00Z',
    updatedAt: '2026-09-20T10:00:00Z',
  },
  {
    id: 'cnt-3',
    contractNumber: 'CTR-2020-008',
    employeeId: 'emp-3',
    employeeName: 'Joaquim Alberto Quaresma',
    employeeCode: 'EMP-003',
    departmentName: 'Contabilidade e Finanças',
    positionName: 'Contabilista Sénior',
    type: 'TEMPO_INDETERMINADO',
    typeName: 'Tempo Indeterminado',
    startDate: '2020-01-10',
    baseSalary: 720000,
    status: 'ATIVO',
    notes: 'Contrato regular sem pendências.',
    signedDate: '2020-01-10',
    isSigned: true,
    createdAt: '2020-01-10T08:30:00Z',
    updatedAt: '2020-01-10T08:30:00Z',
  },
  {
    id: 'cnt-4',
    contractNumber: 'CTR-2024-089',
    employeeId: 'emp-4',
    employeeName: 'Zacarias Francisco Gouveia',
    employeeCode: 'EMP-004',
    departmentName: 'Operações e Logística',
    positionName: 'Coordenador de Logística e Armazém',
    type: 'TERMO_CERTO',
    typeName: 'Termo Certo (24 Meses)',
    startDate: '2024-09-15',
    endDate: '2026-09-15', // Vencido! Alerta VERMELHO!
    durationMonths: 24,
    baseSalary: 450000,
    status: 'TERMINADO',
    notes: 'Contrato terminou a 15 de Setembro de 2026. Necessária deliberação urgente de renovação.',
    signedDate: '2024-09-15',
    isSigned: true,
    createdAt: '2024-09-15T10:00:00Z',
    updatedAt: '2026-09-16T11:00:00Z',
  },
  {
    id: 'cnt-5',
    contractNumber: 'CTR-2022-019',
    employeeId: 'emp-5',
    employeeName: 'Helena Maria de Carvalho',
    employeeCode: 'EMP-005',
    departmentName: 'Comercial e Vendas',
    positionName: 'Gestor Comercial e de Contas',
    type: 'TEMPO_INDETERMINADO',
    typeName: 'Tempo Indeterminado',
    startDate: '2022-02-01',
    baseSalary: 620000,
    status: 'ATIVO',
    notes: 'Contrato com adenda de comissões por volume de vendas.',
    signedDate: '2022-02-01',
    isSigned: true,
    createdAt: '2022-02-01T08:00:00Z',
    updatedAt: '2022-02-01T08:00:00Z',
  },
  {
    id: 'cnt-6',
    contractNumber: 'CTR-2024-031',
    employeeId: 'emp-6',
    employeeName: 'Feliciano Pedro Ndongala',
    employeeCode: 'EMP-006',
    departmentName: 'Tecnologia da Informação',
    positionName: 'Administrador de Redes e Infraestrutura',
    type: 'TERMO_CERTO',
    typeName: 'Termo Certo (36 Meses)',
    startDate: '2024-04-01',
    endDate: '2027-04-01',
    durationMonths: 36,
    baseSalary: 550000,
    status: 'ATIVO',
    notes: 'Em vigor regular com 242 dias decorridos.',
    signedDate: '2024-04-01',
    isSigned: true,
    createdAt: '2024-04-01T09:00:00Z',
    updatedAt: '2024-04-01T09:00:00Z',
  },
];

export const initialDocuments: DocumentItem[] = [
  {
    id: 'doc-1',
    name: 'Bilhete de Identidade - Mateus Cassoma',
    fileName: 'BI_Mateus_Cassoma_003418291LA042.pdf',
    fileSize: 1420500,
    fileType: 'application/pdf',
    category: 'BI',
    categoryName: 'Bilhete de Identidade',
    employeeId: 'emp-1',
    employeeName: 'Mateus Domingos Cassoma',
    issueDate: '2020-04-10',
    expiryDate: '2030-04-10',
    uploadDate: '2021-03-01T10:15:00Z',
    uploadedBy: 'Ana Paula Lourenço',
    notes: 'Documento original verificado presencialmente.',
    status: 'VALIDO',
    fileUrl: '/data/uploads/bi_mateus_cassoma.pdf',
    folderPath: 'EMPRESA/FUNCIONÁRIOS/EMP-001',
  },
  {
    id: 'doc-2',
    name: 'Contrato Assinado - Mateus Cassoma',
    fileName: 'Contrato_Assinado_CTR-2021-001.pdf',
    fileSize: 2890000,
    fileType: 'application/pdf',
    category: 'CONTRATO_ASSINADO',
    categoryName: 'Contrato Assinado',
    employeeId: 'emp-1',
    employeeName: 'Mateus Domingos Cassoma',
    issueDate: '2021-03-01',
    uploadDate: '2021-03-05T14:30:00Z',
    uploadedBy: 'Ana Paula Lourenço',
    notes: 'Exemplar com rubricas e assinatura reconhecida.',
    status: 'VALIDO',
    fileUrl: '/data/uploads/contrato_assinado_mateus.pdf',
    folderPath: 'EMPRESA/CONTRATOS',
  },
  {
    id: 'doc-3',
    name: 'Bilhete de Identidade - Joaquim Quaresma',
    fileName: 'BI_Joaquim_Quaresma.pdf',
    fileSize: 980400,
    fileType: 'application/pdf',
    category: 'BI',
    categoryName: 'Bilhete de Identidade',
    employeeId: 'emp-3',
    employeeName: 'Joaquim Alberto Quaresma',
    issueDate: '2019-01-20',
    expiryDate: '2026-10-10', // Expirando em ~18 dias! Alerta!
    uploadDate: '2020-01-10T11:00:00Z',
    uploadedBy: 'Ana Paula Lourenço',
    notes: 'Atenção: BI expira em Outubro de 2026. Solicitada renovação ao colaborador.',
    status: 'PENDENTE',
    fileUrl: '/data/uploads/bi_joaquim_quaresma.pdf',
    folderPath: 'EMPRESA/FUNCIONÁRIOS/EMP-003',
  },
  {
    id: 'doc-4',
    name: 'Atestado Médico - Joaquim Quaresma',
    fileName: 'Atestado_Medico_2026.pdf',
    fileSize: 740100,
    fileType: 'application/pdf',
    category: 'ATESTADO_MEDICO',
    categoryName: 'Atestado Médico',
    employeeId: 'emp-3',
    employeeName: 'Joaquim Alberto Quaresma',
    issueDate: '2026-08-01',
    expiryDate: '2027-08-01',
    uploadDate: '2026-08-05T09:20:00Z',
    uploadedBy: 'Ana Paula Lourenço',
    notes: 'Exame anual de saúde e aptidão física no trabalho.',
    status: 'VALIDO',
    fileUrl: '/data/uploads/atestado_joaquim.pdf',
    folderPath: 'EMPRESA/FUNCIONÁRIOS/EMP-003',
  },
  {
    id: 'doc-5',
    name: 'Certificado de Habilitações Literárias - Cláudia Oliveira',
    fileName: 'Licenciatura_Gestao_RH_Claudia.pdf',
    fileSize: 3200100,
    fileType: 'application/pdf',
    category: 'CERTIFICADO',
    categoryName: 'Certificado de Habilitações',
    employeeId: 'emp-2',
    employeeName: 'Cláudia Beatriz de Oliveira',
    issueDate: '2018-07-25',
    uploadDate: '2022-05-15T12:00:00Z',
    uploadedBy: 'Ana Paula Lourenço',
    notes: 'Licenciatura em Gestão de Recursos Humanos pela Universidade Católica.',
    status: 'VALIDO',
    fileUrl: '/data/uploads/certificado_claudia.pdf',
    folderPath: 'EMPRESA/FUNCIONÁRIOS/EMP-002',
  },
  {
    id: 'doc-6',
    name: 'Comprovativo de NIF da Empresa',
    fileName: 'Certidao_NIF_Delta_Associados.pdf',
    fileSize: 1100200,
    fileType: 'application/pdf',
    category: 'DECLARACAO',
    categoryName: 'Declaração Institucional',
    uploadDate: '2025-01-05T10:00:00Z',
    uploadedBy: 'Carlos Alberto Ferreira',
    notes: 'Documento fiscal oficial da Administração Geral Tributária (AGT).',
    status: 'VALIDO',
    fileUrl: '/data/uploads/certidao_nif_empresa.pdf',
    folderPath: 'EMPRESA',
  },
  {
    id: 'doc-7',
    name: 'Cartão de Vacinas / Certificado Covid - Zacarias Gouveia',
    fileName: 'Certificado_Vacinas_Zacarias.pdf',
    fileSize: 620000,
    fileType: 'application/pdf',
    category: 'OUTRO',
    categoryName: 'Outro Documento',
    employeeId: 'emp-4',
    employeeName: 'Zacarias Francisco Gouveia',
    issueDate: '2021-04-10',
    expiryDate: '2024-04-10', // Expirado!
    uploadDate: '2023-08-01T15:00:00Z',
    uploadedBy: 'Ana Paula Lourenço',
    notes: 'Documento com validade expirada.',
    status: 'EXPIRADO',
    fileUrl: '/data/uploads/vacina_zacarias.pdf',
    folderPath: 'EMPRESA/FUNCIONÁRIOS/EMP-004',
  },
];

export const initialVacations: Vacation[] = [
  {
    id: 'vac-1',
    employeeId: 'emp-3',
    employeeName: 'Joaquim Alberto Quaresma',
    employeeCode: 'EMP-003',
    departmentName: 'Contabilidade e Finanças',
    startDate: '2026-09-15',
    endDate: '2026-09-30',
    daysCount: 15,
    type: 'FERIAS_ANUAIS',
    typeName: 'Férias Anuais Regulamentares',
    status: 'EM_CURSO',
    notes: '1º Período do ano letivo de 2026.',
    approvedBy: 'Carlos Alberto Ferreira',
    approvedAt: '2026-08-25T11:00:00Z',
    createdAt: '2026-08-20T09:00:00Z',
  },
  {
    id: 'vac-2',
    employeeId: 'emp-1',
    employeeName: 'Mateus Domingos Cassoma',
    employeeCode: 'EMP-001',
    departmentName: 'Tecnologia da Informação',
    startDate: '2026-11-01',
    endDate: '2026-11-22',
    daysCount: 22,
    type: 'FERIAS_ANUAIS',
    typeName: 'Férias Anuais Regulamentares',
    status: 'APROVADA',
    notes: 'Aprovadas sem coincidência de turnos na equipa de desenvolvimento.',
    approvedBy: 'Ana Paula Lourenço',
    approvedAt: '2026-09-10T16:00:00Z',
    createdAt: '2026-09-05T14:00:00Z',
  },
  {
    id: 'vac-3',
    employeeId: 'emp-2',
    employeeName: 'Cláudia Beatriz de Oliveira',
    employeeCode: 'EMP-002',
    departmentName: 'Recursos Humanos',
    startDate: '2026-12-15',
    endDate: '2026-12-30',
    daysCount: 15,
    type: 'FERIAS_ANUAIS',
    typeName: 'Férias Anuais Regulamentares',
    status: 'PENDENTE',
    notes: 'Aguardando validação da direção executiva para o período natalício.',
    createdAt: '2026-09-18T10:30:00Z',
  },
  {
    id: 'vac-4',
    employeeId: 'emp-5',
    employeeName: 'Helena Maria de Carvalho',
    employeeCode: 'EMP-005',
    departmentName: 'Comercial e Vendas',
    startDate: '2026-05-02',
    endDate: '2026-05-24',
    daysCount: 22,
    type: 'FERIAS_ANUAIS',
    typeName: 'Férias Anuais Regulamentares',
    status: 'CONCLUIDA',
    notes: 'Gozadas na totalidade sem interrupções.',
    approvedBy: 'Margarida dos Santos',
    approvedAt: '2026-04-15T09:00:00Z',
    createdAt: '2026-04-10T08:00:00Z',
  },
];

export const initialAbsences: Absence[] = [
  {
    id: 'abs-1',
    employeeId: 'emp-2',
    employeeName: 'Cláudia Beatriz de Oliveira',
    employeeCode: 'EMP-002',
    departmentName: 'Recursos Humanos',
    date: '2026-09-08',
    hours: 8,
    type: 'JUSTIFICADA',
    typeName: 'Falta Justificada (Consulta Médica)',
    reason: 'Consulta médica de rotina e realização de exames complementares.',
    isJustified: true,
    documentProofName: 'Declaracao_Clinica_Luanda.pdf',
    documentProofUrl: '/data/uploads/declaracao_medica_claudia.pdf',
    notes: 'Comprovativo médico entregue e validado pela chefia.',
    registeredBy: 'Ana Paula Lourenço',
    createdAt: '2026-09-09T08:30:00Z',
  },
  {
    id: 'abs-2',
    employeeId: 'emp-4',
    employeeName: 'Zacarias Francisco Gouveia',
    employeeCode: 'EMP-004',
    departmentName: 'Operações e Logística',
    date: '2026-09-14',
    hours: 8,
    type: 'INJUSTIFICADA',
    typeName: 'Falta Injustificada',
    reason: 'Não compareceu ao turno matinal e não atendeu as tentativas de contacto da coordenação.',
    isJustified: false,
    notes: 'Sujeito a desconto salarial correspondente a 1 dia útil de trabalho.',
    registeredBy: 'Ana Paula Lourenço',
    createdAt: '2026-09-14T17:00:00Z',
  },
  {
    id: 'abs-3',
    employeeId: 'emp-6',
    employeeName: 'Feliciano Pedro Ndongala',
    employeeCode: 'EMP-006',
    departmentName: 'Tecnologia da Informação',
    date: '2026-09-18',
    time: '10:30',
    hours: 2,
    type: 'ATRASO',
    typeName: 'Atraso Justificado',
    reason: 'Avaria mecânica na viatura de transporte público na via expressa.',
    isJustified: true,
    notes: 'Notificou o coordenador de TI com antecedência por telefone.',
    registeredBy: 'Carlos Alberto Ferreira',
    createdAt: '2026-09-18T11:00:00Z',
  },
  {
    id: 'abs-4',
    employeeId: 'emp-5',
    employeeName: 'Helena Maria de Carvalho',
    employeeCode: 'EMP-005',
    departmentName: 'Comercial e Vendas',
    date: '2026-09-02',
    hours: 4,
    type: 'AUSENCIA_AUTORIZADA',
    typeName: 'Ausência Autorizada em Serviço Externo',
    reason: 'Reunião de negociação e apresentação de proposta comercial junto de cliente institucional.',
    isJustified: true,
    notes: 'Deslocação oficial autorizada.',
    registeredBy: 'Margarida dos Santos',
    createdAt: '2026-09-02T14:00:00Z',
  },
];

export const initialSalaryHistory: SalaryHistory[] = [
  {
    id: 'sh-1',
    employeeId: 'emp-1',
    employeeName: 'Mateus Domingos Cassoma',
    previousSalary: 750000,
    newSalary: 950000,
    changeDate: '2025-01-01',
    reason: 'Promoção a Líder Técnico de Sistemas e revisão anual de mérito.',
    changedBy: 'Carlos Alberto Ferreira',
    createdAt: '2025-01-02T10:00:00Z',
  },
  {
    id: 'sh-2',
    employeeId: 'emp-2',
    employeeName: 'Cláudia Beatriz de Oliveira',
    previousSalary: 380000,
    newSalary: 480000,
    changeDate: '2025-06-01',
    reason: 'Ajuste de enquadramento funcional e atribuição de responsabilidades de folha.',
    changedBy: 'Carlos Alberto Ferreira',
    createdAt: '2025-06-01T09:00:00Z',
  },
  {
    id: 'sh-3',
    employeeId: 'emp-3',
    employeeName: 'Joaquim Alberto Quaresma',
    previousSalary: 600000,
    newSalary: 720000,
    changeDate: '2024-01-15',
    reason: 'Ajuste salarial decorrente de certificação em contabilidade internacional.',
    changedBy: 'Carlos Alberto Ferreira',
    createdAt: '2024-01-15T11:00:00Z',
  },
];

export const initialPayrollSheets: PayrollSheet[] = [
  {
    id: 'pyr-2026-09',
    referenceMonth: '2026-09',
    title: 'Folha Salarial - Setembro de 2026',
    totalEmployees: 6,
    totalGross: 3770000,
    totalAllowances: 720000,
    totalBonuses: 150000,
    totalDeductions: 395000,
    totalNet: 4245000,
    isLocked: false,
    createdAt: '2026-09-01T08:00:00Z',
    updatedAt: '2026-09-22T08:00:00Z',
    entries: [
      {
        id: 'pe-1',
        employeeId: 'emp-1',
        employeeCode: 'EMP-001',
        employeeName: 'Mateus Domingos Cassoma',
        positionName: 'Engenheiro de Software Sénior',
        departmentName: 'Tecnologia da Informação',
        bankName: 'BAI',
        accountNumber: '1428590123',
        iban: 'AO06004000001428590123101',
        baseSalary: 950000,
        mealAllowance: 60000,
        transportAllowance: 60000,
        otherAllowances: 30000,
        bonus: 50000,
        deductions: 95000,
        absencesCount: 0,
        absenceDeductions: 0,
        netSalary: 1055000,
        status: 'PENDENTE',
      },
      {
        id: 'pe-2',
        employeeId: 'emp-2',
        employeeCode: 'EMP-002',
        employeeName: 'Cláudia Beatriz de Oliveira',
        positionName: 'Técnico Sénior de RH',
        departmentName: 'Recursos Humanos',
        bankName: 'BMA',
        accountNumber: '9847120394',
        iban: 'AO06005500009847120394102',
        baseSalary: 480000,
        mealAllowance: 60000,
        transportAllowance: 60000,
        otherAllowances: 0,
        bonus: 0,
        deductions: 48000,
        absencesCount: 1, // justificada, sem desconto
        absenceDeductions: 0,
        netSalary: 552000,
        status: 'PENDENTE',
      },
      {
        id: 'pe-3',
        employeeId: 'emp-3',
        employeeCode: 'EMP-003',
        employeeName: 'Joaquim Alberto Quaresma',
        positionName: 'Contabilista Sénior',
        departmentName: 'Contabilidade e Finanças',
        bankName: 'BFA',
        accountNumber: '4481029384',
        iban: 'AO06000600004481029384109',
        baseSalary: 720000,
        mealAllowance: 60000,
        transportAllowance: 60000,
        otherAllowances: 20000,
        bonus: 0,
        deductions: 72000,
        absencesCount: 0,
        absenceDeductions: 0,
        netSalary: 788000,
        status: 'PENDENTE',
      },
      {
        id: 'pe-4',
        employeeId: 'emp-4',
        employeeCode: 'EMP-004',
        employeeName: 'Zacarias Francisco Gouveia',
        positionName: 'Coordenador de Logística e Armazém',
        departmentName: 'Operações e Logística',
        bankName: 'Banco Sol',
        accountNumber: '7729104812',
        iban: 'AO06004400007729104812105',
        baseSalary: 450000,
        mealAllowance: 60000,
        transportAllowance: 60000,
        otherAllowances: 0,
        bonus: 0,
        deductions: 45000,
        absencesCount: 1, // falta injustificada
        absenceDeductions: 15000, // 450000 / 30 = 15000
        netSalary: 510000,
        status: 'PENDENTE',
      },
      {
        id: 'pe-5',
        employeeId: 'emp-5',
        employeeCode: 'EMP-005',
        employeeName: 'Helena Maria de Carvalho',
        positionName: 'Gestor Comercial e de Contas',
        departmentName: 'Comercial e Vendas',
        bankName: 'BAI',
        accountNumber: '3318290192',
        iban: 'AO06004000003318290192103',
        baseSalary: 620000,
        mealAllowance: 60000,
        transportAllowance: 60000,
        otherAllowances: 0,
        bonus: 100000, // Prémio de metas comerciais
        deductions: 72000,
        absencesCount: 0,
        absenceDeductions: 0,
        netSalary: 768000,
        status: 'PENDENTE',
      },
      {
        id: 'pe-6',
        employeeId: 'emp-6',
        employeeCode: 'EMP-006',
        employeeName: 'Feliciano Pedro Ndongala',
        positionName: 'Administrador de Redes e Infraestrutura',
        departmentName: 'Tecnologia da Informação',
        bankName: 'BMA',
        accountNumber: '5519283746',
        iban: 'AO06005500005519283746108',
        baseSalary: 550000,
        mealAllowance: 60000,
        transportAllowance: 60000,
        otherAllowances: 0,
        bonus: 0,
        deductions: 55000,
        absencesCount: 1, // Atraso justificado
        absenceDeductions: 0,
        netSalary: 615000,
        status: 'PENDENTE',
      },
    ],
  },
  {
    id: 'pyr-2026-08',
    referenceMonth: '2026-08',
    title: 'Folha Salarial - Agosto de 2026',
    totalEmployees: 6,
    totalGross: 3770000,
    totalAllowances: 720000,
    totalBonuses: 80000,
    totalDeductions: 380000,
    totalNet: 4190000,
    isLocked: true,
    lockedAt: '2026-08-31T18:00:00Z',
    lockedBy: 'Manuel Sebastião Neves',
    createdAt: '2026-08-01T08:00:00Z',
    updatedAt: '2026-08-31T18:00:00Z',
    entries: [
      {
        id: 'pe-aug-1',
        employeeId: 'emp-1',
        employeeCode: 'EMP-001',
        employeeName: 'Mateus Domingos Cassoma',
        positionName: 'Engenheiro de Software Sénior',
        departmentName: 'Tecnologia da Informação',
        bankName: 'BAI',
        accountNumber: '1428590123',
        iban: 'AO06004000001428590123101',
        baseSalary: 950000,
        mealAllowance: 60000,
        transportAllowance: 60000,
        otherAllowances: 30000,
        bonus: 0,
        deductions: 95000,
        absencesCount: 0,
        absenceDeductions: 0,
        netSalary: 1005000,
        paymentDate: '2026-08-31',
        status: 'PAGO',
      },
    ],
  },
];

export const initialNotifications: NotificationItem[] = [
  {
    id: 'notif-1',
    title: 'Contrato a Terminar Brevemente',
    message: 'O contrato de trabalho de Cláudia Beatriz de Oliveira (CTR-2025-042) termina em menos de 10 dias (01/10/2026).',
    type: 'WARNING',
    category: 'CONTRATO',
    link: '/contratos',
    read: false,
    createdAt: '2026-09-21T09:00:00Z',
  },
  {
    id: 'notif-2',
    title: 'Contrato Vencido',
    message: 'O contrato de Zacarias Francisco Gouveia (CTR-2024-089) venceu a 15/09/2026. Ação necessária imediata.',
    type: 'ALERT',
    category: 'CONTRATO',
    link: '/contratos',
    read: false,
    createdAt: '2026-09-16T08:00:00Z',
  },
  {
    id: 'notif-3',
    title: 'Documento Próximo da Validade',
    message: 'O Bilhete de Identidade de Joaquim Alberto Quaresma expira a 10/10/2026.',
    type: 'WARNING',
    category: 'DOCUMENTO',
    link: '/documentos',
    read: false,
    createdAt: '2026-09-20T11:30:00Z',
  },
  {
    id: 'notif-4',
    title: 'Férias Pendentes de Aprovação',
    message: 'Cláudia Beatriz de Oliveira submeteu pedido de férias para Dezembro de 2026 (15 dias).',
    type: 'INFO',
    category: 'FERIAS',
    link: '/ferias',
    read: false,
    createdAt: '2026-09-18T10:35:00Z',
  },
  {
    id: 'notif-5',
    title: 'Folha Salarial em Aberto',
    message: 'A folha salarial de Setembro de 2026 encontra-se aberta para revisão e validação.',
    type: 'INFO',
    category: 'FOLHA_SALARIAL',
    link: '/salarios',
    read: true,
    createdAt: '2026-09-15T08:00:00Z',
  },
];

export const initialAuditLogs: AuditLog[] = [
  {
    id: 'log-1',
    userId: 'usr-1',
    userName: 'Carlos Alberto Ferreira',
    userRole: 'ADMINISTRADOR',
    action: 'Criação de Contrato',
    entity: 'Contrato',
    entityId: 'cnt-2',
    details: 'Utilizador Carlos Ferreira emitiu contrato CTR-2025-042 da funcionária Cláudia Oliveira.',
    ipAddress: '192.168.1.10',
    timestamp: '2026-09-20T10:00:00Z',
  },
  {
    id: 'log-2',
    userId: 'usr-2',
    userName: 'Ana Paula Lourenço',
    userRole: 'RH',
    action: 'Upload de Documento',
    entity: 'Documento',
    entityId: 'doc-3',
    details: 'Utilizador Ana Lourenço carregou o documento BI_Joaquim_Quaresma.pdf na pasta do funcionário.',
    ipAddress: '192.168.1.15',
    timestamp: '2026-09-19T14:22:00Z',
  },
  {
    id: 'log-3',
    userId: 'usr-1',
    userName: 'Carlos Alberto Ferreira',
    userRole: 'ADMINISTRADOR',
    action: 'Alteração Salarial',
    entity: 'Salário',
    entityId: 'emp-1',
    details: 'Utilizador Carlos alterou o salário do funcionário EMP-001 (Mateus Cassoma) de 750.000 para 950.000 Kz.',
    ipAddress: '192.168.1.10',
    timestamp: '2026-09-15T16:40:00Z',
  },
  {
    id: 'log-4',
    userId: 'usr-3',
    userName: 'Manuel Sebastião Neves',
    userRole: 'CONTABILIDADE',
    action: 'Fecho de Folha Salarial',
    entity: 'Folha Salarial',
    entityId: 'pyr-2026-08',
    details: 'Utilizador Manuel Neves efetuou o bloqueio oficial da folha salarial de Agosto de 2026.',
    ipAddress: '192.168.1.20',
    timestamp: '2026-08-31T18:00:00Z',
  },
  {
    id: 'log-5',
    userId: 'usr-2',
    userName: 'Ana Paula Lourenço',
    userRole: 'RH',
    action: 'Registo de Falta',
    entity: 'Falta',
    entityId: 'abs-2',
    details: 'Utilizador Ana Lourenço registou falta injustificada para o funcionário Zacarias Gouveia no dia 14/09.',
    ipAddress: '192.168.1.15',
    timestamp: '2026-09-14T17:00:00Z',
  },
];
